version: '3.7'

services:
  web:
    build: ./services/web
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.venv.dev
    depends_on:
      - db
    environment:
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=baby_app
      - POSTGRES_PASSWORD=baby_app
      - POSTGRES_DB=baby_app_dev

volumes:
  postgres_data:
